use_frameworks!

platform :ios, '12.0'

target 'LifeHash_Example' do
    pod 'WolfCache'
    pod 'WolfAutolayout'
    pod 'WolfViews'
    pod 'WolfColor'
    pod 'WolfCore'
    pod 'WolfViewControllers'
    pod 'WolfImage'

    pod 'LifeHash', :path => '../'

    target 'LifeHash_Tests' do
        inherit! :search_paths
    end
end
