use_frameworks!

platform :ios, '12.0'

target 'LifeHash_Example' do
    pod 'WolfAutolayout'
    pod 'WolfViews'
    pod 'WolfColor'
    pod 'WolfWith'
    pod 'WolfNesting'
    pod 'WolfConcurrency'

    pod 'LifeHash', :path => '../'

    target 'LifeHash_Tests' do
        inherit! :search_paths
    end
end
